# Generated by Django 5.2.6 on 2025-09-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hariapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_db',
            old_name='car_model_no',
            new_name='car_modelno',
        ),
    ]
